# Make sure to check the goreleaser documentation at http://goreleaser.com

project_name: simple-yaml-iterator

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
archives:
- format: binary
  # Read more here: https://goreleaser.com/customization/#packaging-only-the-binaries
  files:
  - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
